# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web_errors.rake

module Slack
  module Web
    module Api
      module Errors
        class CannotUnfurlUrl < SlackError; end
      end
    end
  end
end
